version: '3.8'

services:
  waba:
    # image: kacestudio/codeigniter3-dev
    # command: sh -c chmod +x /var/lib/nginx -R
    build: .
    restart: always
    working_dir: /var/www/html
    ports:
      - 8111:80
    volumes:
      - ./waba-client-app:/var/www/html
      # - ./nginx/waba.conf:/etc/nginx/nginx.conf
      # - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      DB_HOSTNAME: mysql-8
  jarvis:
    image: kacestudio/codeigniter3-dev
    restart: always
    working_dir: /var/www/html
    ports:
      - 8081:80
    volumes:
      - ./jarvis:/var/www/html
      - ./nginx/jarvis.conf:/etc/nginx/nginx.conf
  mysql-8:
    image: mysql:8.0.32
    container_name: mysql-8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306
    volumes:
      - ./mysql-8:/var/lib/mysql
  mysql-5:
    image: mysql:5.7.33
    container_name: mysql-5
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3307:3306
    volumes:
      - ./mysql-5:/var/lib/mysql
